# Generated by Django 5.2.6 on 2025-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Seating', 'Seating'), ('Tables', 'Tables'), ('Tent', 'Tent'), ('Venues', 'Venues'), ('Sport Equipment', 'Sport Equipment'), ('Cooling Ventilation', 'Cooling Ventilation'), ('Water Supply', 'Water Supply'), ('Electrical Accessories', 'Electrical Accessories'), ('Audio-Visual Equipment', 'Audio-Visual Equipment'), ('Transportation', 'Transportation')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='available',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
