# Generated by Django 5.2.6 on 2025-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_category_remove_passwordresetcode_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='No description yet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
